Shopify/spoom

lib/spoom/cli.rb, lib/spoom/cli/commands/run.rb, lib/spoom/sorbet.rb, lib/spoom/sorbet/errors.rb, test/spoom/cli/commands/config_test.rb, test/spoom/cli/commands/lsp_test.rb, test/spoom/cli/commands/run_test.rb, test/spoom/sorbet/errors_test.rb
This pull-request introduces `Spoom::Sorbet::Errors::parser` that can be used to parse errors from Sorbet output:
```ruby
errors = Spoom::Sorbet::Errors::Parser.parse_string(<<~ERR)
lib/test/file.rb:80: unexpected token "end" https://srb.help/2001
80 |end
^^^
ERR
assert_equal(1, errors.size)
error = errors.first
assert_equal("lib/test/file.rb", error.file)
assert_equal(80, error.line)
assert_equal("unexpected token \"end\"", error.message)
assert_equal(2001, error.code)
assert_equal(["80 |end", "^^^"], error.more.each(&:strip!))
```
This can also be used in command line to filter the errors produced by Sorbet.
For example to show only the first 5 `7004` errors
```bash
spoom tc --code 7004 -limit 5
```
To sort  errors by their code instead of location:
```bash
spoom tc --sort code
```
See …
=> Add a parser for Sorbet errors

Gemfile, Gemfile.lock
This change allows debugging with `pry`. Pause execution and inspect by adding `require 'pry'; binding.pry`.
=> Adds byebug and pry-byebug to Gemfile

lib/spoom/sorbet.rb, test/spoom/sorbet/version_test.rb, test/support/project_without_sorbet/Gemfile, test/support/project_without_sorbet/Gemfile.lock
Add a service to easily get the version from Sorbet:
```ruby
puts Spoom::Sorbet.srb_version("my_project") # "0.5.5808"
```
It returns `nil` if `srb` is not installed:
```ruby
puts Spoom::Sorbet.srb_version("my_project_without_srb") # nil
```
=> Add `srb_version` service

lib/spoom/cli/commands/run.rb, lib/spoom/sorbet.rb, lib/spoom/sorbet/metrics.rb, test/spoom/cli/commands/run_test.rb, test/spoom/sorbet/metrics_test.rb
Add the command `spoom tc metrics` and the associated parsing methods.
This commands displays the metrics collected by Sorbet during typechecking (when the option `--metrics-file` is passed):
```
$ spoom tc metrics
Sigils:
files: 6
true: 6 (100%)
Methods:
methods: 22
signatures: 2 (9%)
Sends:
sends: 51
typed: 47 (92%)
```
As an example, the underlying methods are already used by the new version of SorbetMetrics: https://github.com/Shopify/sorbet-metrics/blob/master/lib/sorbet_metrics/actions/collect_sorbet_metrics.rb#L21
=> Add `spoom tc metrics`

Gemfile.lock, lib/spoom/sorbet/metrics.rb, sorbet/rbi/gems/colorize@0.8.1.rbi, sorbet/rbi/gems/thor@1.0.1.rbi, test/spoom/cli/commands/run_test.rb, test/spoom/sorbet/metrics_test.rb, test/spoom/sorbet/version_test.rb, test/support/project/Gemfile.lock
Running Spoom now displays the count of classes and modules in the project:
```
$ bundle exec spoom tc metrics
No errors! Great job.
Sigils:
files: 52
ignore: 1 (1%)
true: 46 (88%)
strict: 5 (9%)
Classes & Modules:
classes: 276 (including singleton classes)
modules: 46
Methods:
methods: 1660
signatures: 85 (5%)
Sends:
sends: 2763
typed: 2183 (79%)
```
Note that the classes count also include singleton classes.
=> Spoom displays the count of classes and modules found in the project

lib/spoom/sorbet/metrics.rb, test/spoom/sorbet/metrics_test.rb
Applying the nice trick showed by @paracycle here: https://github.com/Shopify/spoom/pull/11#discussion_r493772669
Signed-off-by: Alexandre Terrasa <alexandre.terrasa@shopify.com>
=> Initialize metrics object with `0`s

.rubocop.yml, README.md, lib/spoom/cli.rb, lib/spoom/cli/commands/config.rb, lib/spoom/file_tree.rb, test/spoom/cli/commands/cli_test.rb, test/spoom/cli/commands/config_test.rb, test/spoom/file_tree_test.rb, test/support/project/task1.rake, test/support/project/task2.rake
This PR introduces `FileTree` a representation for files hierarchy so we can print them properly in terminal.
Demo `spoom files` (the color depends on the strictness level of the file):
Demo `spoom files --no-color`:
=> Introduce FileTree and command `spoom files`

lib/spoom/sorbet/metrics.rb, test/spoom/sorbet/metrics_test.rb
Those metrics are only initialized if you pass specific options to Sorbet:
```
--metrics-branch branch   Branch to report in metrics export (default:
none)
--metrics-sha sha1        Sha1 to report in metrics export (default:
none)
--metrics-repo repo       Repo to report in metrics export (default:
none)
--metrics-extra-tags key1=value1,key2=value2
Extra tags to report, comma separated
(default: "")
```
We actually don't care about them so let's remove the fields.
=> Clean some unused metrics fields

lib/spoom/cli/commands/bump.rb
`srb tc` could return many errors from the same file. Only change sigil once per file.
=> Speed up the bump task

README.md, lib/spoom/cli/commands/coverage.rb, lib/spoom/git.rb, lib/spoom/snapshot.rb, lib/spoom/timeline.rb, test/spoom/cli/commands/coverage_test.rb, test/spoom/git_test.rb, test/spoom/git_test_helper.rb, test/spoom/timeline_test.rb
This command basically run `spoom coverage snapshot` for each month your project has existed.
It finds the first commit sorbet was introduced, then selects one commit by month until now to build the timeline.
This can be controlled with the `--from` and `--to` options.
The `--save-dir` option allows the user the save the timeline in JSON format.
=> Add `spoom coverage timeline`

README.md, lib/spoom/cli.rb, lib/spoom/cli/command_helper.rb, lib/spoom/cli/commands/config.rb, lib/spoom/cli/commands/coverage.rb, lib/spoom/cli/commands/lsp.rb, lib/spoom/cli/commands/run.rb, lib/spoom/config.rb, lib/spoom/file_tree.rb, lib/spoom/sorbet/lsp.rb, lib/spoom/sorbet/lsp/base.rb, lib/spoom/sorbet/lsp/structures.rb, test/spoom/cli/commands/cli_test.rb, test/spoom/cli/commands/config_test.rb, test/spoom/cli/commands/coverage_test.rb, test/spoom/cli/commands/lsp_test.rb, test/spoom/cli/commands/run_test.rb
This pull-request adds a `--path` option to `spoom` so it can run in a different directory.
Why is it useful?
* When working on new features, one can use `--path` to test the feature on different projects without having to change their Gemfiles.
* Spoom can be used as a system wide gem and ran on projects that does not use spoom (some commands even work if the project doesn't have sorbet installed).
I also added a few tests ensuring each command works correctly with the `--path` option.
=> Add `--path` option

README.md, lib/spoom/cli/commands/coverage.rb
As discussed in #23 with @paracycle we should provide a way to collect the snapshot data from an installed bundle.
This PR introduces `spoom coverage timeline --bundle-install` which will run `bundle install` for each commit in the timeline before running Sorbet to collect the metrics.
If a `--bundle-install` is used and bundle install doesn't finishes properly, the commit is skipped.
=> Add spoom coverage timeline --bundle-install option

lib/spoom/cli/commands/coverage.rb, lib/spoom/snapshot.rb, lib/spoom/sorbet.rb, test/spoom/cli/commands/coverage_test.rb, test/spoom/sorbet/version_test.rb, test/test_helper.rb
Spoom now provides two ways to get the Sorbet version used:
1. Through `Spoom::Sorbet.srb_version` which runs `bundle exec sorbet --version`.
2. Through `Spoom::Sorbet.srb_version_from_gemfile_lock` which parses the content of the `Gemfile.lock` for the current commit.
This makes us able to save the sorbet version used for a snapshot for the two cases we have in `spoom timeline`:
1. We don't use `--bundle-install` so we read the version from the `Gemfile.lock` (useful when running the timeline from another context, like we do in `sorbet-metrics` for core).
2. We use `--bundle-install` so we can just ask Sorbet.
=> Save sorbet-version used in snapshots

README.md, lib/spoom/cli/commands/coverage.rb, lib/spoom/snapshot.rb, test/spoom/cli/commands/coverage_test.rb
This PR does two things: 
1. First, this PR splits the current `--save-dir PATH` into two options: `--save` to ask for save and `--save-dir` to specify the path. This is because I'm tired of typing `--save-dir PATH` when I just want to save to the default dir.
2. Then it reuses these two options on `spoom coverage snapshot` so I don't have to run `spoom coverage snapshot --from F --to T` just to save the snapshot on the current commit (this also makes it easier to get the upcoming `spoom report` feature working with default dirs).
=> Add `--save` to `spoom coverage`

lib/spoom/cli/commands/coverage.rb, lib/spoom/snapshot.rb, test/spoom/snapshot_test.rb
Also add to metrics to the snapshot:
* timestamp
* sorbet run time
And a test to ensure serialization, deserialization works fine.
=> Allow Snapshot to be saved/loaded with JSON

lib/spoom/cli/commands/coverage.rb, lib/spoom/git.rb, test/spoom/git_test.rb
It's named `_date` but returns a `Time`.
I was about to do the same thing for `Spoom::Timeline::commits_for_dates` but `commits_for_times` was confusing along with `ticks` (like in "one times two"). Let me know if you want me to rename it too.
=> Some renaming inside Spoom::Git

lib/spoom/snapshot.rb, lib/spoom/sorbet.rb, test/spoom/sorbet/version_test.rb
It turns out that you can't even _parse_ a Gemfile.lock from another version Bundle version (it raises).
This PR gets the version from the `Gemfile.lock` manually instead.
I also added a way to specify which gem you want the version from, can be useful to collect the info about `sorbet-runtime` (see test).
=> Manually parse version from Gemfile.lock

lib/spoom/snapshot.rb, test/spoom/cli/commands/coverage_test.rb, test/spoom/snapshot_test.rb
Use #36 to keep track of both `sorbet-static` and `sorbet-runtime` versions.
This can be used to build a graph showing when the versions are diverging:
=> Also store sorbet-runtime version

Gemfile.lock, lib/spoom/snapshot.rb, test/spoom/cli/commands/coverage_test.rb
Since https://github.com/sorbet/sorbet/pull/3446 was merged upstream we can provide a more accurate number for the amount of classes in the project by subtracting the number of singleton classes.
This PR changes the output of `spoom coverage snapshot` and the related tests to reflect that.
=> Add Snapshot metrics for singleton classes

lib/spoom/git.rb, test/spoom/git_test.rb
There is no way to reach this state with normal CLI use but it's possible to get to this state using the API directly.
Since all the methods in this module return an error string + status if something go wrong with the `git` command, we reuse the same mechanism instead of raising for this error so client only have one thing to check.
This change also makes testing with incomplete file hierarchies easier.
=> Avoid crashing on non-existing path when calling `git`

.github/workflows/ruby.yml
So we can fix this error on CI: https://github.com/Shopify/spoom/pull/43/checks?check_run_id=1412893423
=> Update ruby setup version for Github workflow

README.md, lib/spoom/cli/coverage.rb, lib/spoom/coverage.rb, lib/spoom/coverage/d3.rb, lib/spoom/coverage/d3/circle_map.rb, lib/spoom/coverage/report.rb
Add a bunch of options so the user can configure the colors used for each strictness in the visualizations:
```bash
$ spoom coverage report \
--color-true "#648ffe" \
--color-false "#fe6002" \
--color-ignore "#feb000" \
--color-strict "#795ef0" \
--color-strong "#6444f1"
```
Will give the following output:
Helpful for colorblind folks.
=> Allow to customize colors

lib/spoom/cli.rb, lib/spoom/coverage.rb, lib/spoom/coverage/d3/circle_map.rb, lib/spoom/file_tree.rb, lib/spoom/sorbet/sigils.rb, lib/spoom/test_helpers/project.rb, test/spoom/cli/cli_test.rb, test/spoom/file_tree_test.rb, test/spoom/sorbet/sigils_test.rb
Small improvement to the way we generate the FileTree by allowing the user to specify a prefix path to be stripped.
This is particularly useful when running `spoom` from another directory.
For example if I run `spoom files --path /path/to/project` the file tree will be displayed as:
```
/path
/to
/project
file1.rb
file2.rb
```
This is okay for most case but becomes problematic when working with relative paths or really long one.
It's also problematic for the circle map where it create useless circles.
Here's an example before:
After:
Overall it makes the FileTree API easier to use from other tools such as SorbetMetrics.
=> Allow stripping prefix path from FileTree

lib/spoom/cli/bump.rb, lib/spoom/cli/helper.rb, test/spoom/cli/bump_test.rb, test/spoom/cli/config_test.rb, test/spoom/cli/coverage_test.rb, test/spoom/cli/lsp_test.rb, test/spoom/cli/run_test.rb, test/spoom/sorbet/errors_test.rb
This PR brings some improvements to the `spoom bump` command:
* `spoom bump` uses `in_sorbet_project!` and displays an error if ran outside of a Sorbet project
* Some improvements to the error message when ran outside a Sorbet project
* `spoom bump` uses the `--path` option, so we can `spoom bump lib/ --path my/project`
* Avoid reverting files from other directories when bumping files with errors
Also add a few tests to show all the new behavior.
Fixes #10 and #50.
=> Improvements to `spoom bump`

lib/spoom/cli/run.rb, test/spoom/cli/run_test.rb
Make `spoom tc` exit with the correct values.
Fixes #53.
cc. @alunbestor
=> Fix return codes for `spoom tc`

lib/spoom/cli.rb, lib/spoom/cli/bump.rb, lib/spoom/cli/config.rb, lib/spoom/cli/coverage.rb, lib/spoom/cli/lsp.rb, lib/spoom/cli/run.rb, test/spoom/cli/cli_test.rb
Some cleaning around messages displayed from `--help`:
* Always start the description with an uppercase (Like the default help message from `thor`)
* Always use `desc` as the last parameter of the `option` method
* Add missing descriptions for a few options
No real functional change.
=> Uniformize help messages

lib/spoom/cli/helper.rb
`fileutils` was never explicitly required outside of tests (see `test_helpers/project.rb`) and reading the [documentation](https://ruby-doc.org/stdlib-2.7.2/libdoc/fileutils/rdoc/FileUtils.html) it seems `fileutils` needs to be required.
No idea how this was working before 🤷‍♂️ 
Closes #57.
cc. @connorshea
=> Require `fileutils`

README.md, lib/spoom/cli/run.rb, lib/spoom/sorbet/errors.rb, test/spoom/cli/run_test.rb, test/spoom/sorbet/errors_test.rb
Some improvements to `spoom tc`.
To remove duplicated error lines:
```
$ spoom tc -u
```
To format each error line:
```
$ spoom tc -f '%C - %F:%L: %M'
```
Where:
* `%C` is the error code
* `%F` is the file the error is from
* `%L` is the line the error is from
* `%M` is the error message
To hide the `Errors: X` at the end of the list:
```
$ spoom tc --no-count
```
It makes it easier to use spoom with other tools.
For example, to open all the files that contain an error:
```
vim -p `spoom tc -f '%F' -u`
```
=> Add useful options to filter errors

lib/spoom/cli/coverage.rb, lib/spoom/coverage.rb, lib/spoom/sorbet/config.rb, test/spoom/cli/coverage_test.rb, test/spoom/snapshot_test.rb, test/spoom/sorbet/config_test.rb
By default, running `spoom coverage` will output the coverage metrics **including** the RBi files.
This can give misleading metrics when having a large amount of RBIs (for example when they are generated by `tapicoa`).
This PR makes the default to not include RBIs and adds the `--include-rbi` option to count them:
Example for `spoom coverage` on `spoom` itself:
```
Content:
files: 68
modules: 52
classes: 154
methods: 1994
Sigils:
true: 49 (72%)
strict: 19 (28%)
Methods:
with signature: 300 (15%)
without signature: 1694 (85%)
Calls:
typed: 4893 (80%)
untyped: 1246 (20%)
```
Example for `spoom coverage --include-rbi`:
```
Content:
files: 49
modules: 16
classes: 79
methods: 687
Sigils:
true: 30 (61%)
strict: 19 (39%)
Methods:
with signature: 300 (44%)
without signature: 387 (56%)
Calls: …
```
=> Do not include RBI by default in coverage metrics

lib/spoom/sorbet/sigils.rb, test/spoom/cli/bump_test.rb, test/spoom/sorbet/sigils_test.rb
As @masylum found out, when trying to get the sigil from a file, we're reading it with the default encoding: `utf-8`.
This is problematic when reading a file from a different encoding, especially when the file contains special characters like `À coûté 10€`.
This pull-request allows the user to read and write the files with a specific encoding by adding:
* a `encoding:` keyword argument to `Sigils` services
* a `--encoding` option to the `bump` command
Thus, solving the issue raised by #52.
=> Allow bumping files with non-utf8 content

.github/workflows/ruby.yml, README.md, lib/spoom/cli/bump.rb, lib/spoom/version.rb, test/spoom/cli/bump_test.rb
This pull-request adds a few options to `spoom bump` as to make it easier to use in more complex bumps.
1. Add some printing so we see what the command is doing
2. Add `spoom bump --dry to not do anything, just see the changes that might happen
3. Add `spoom bump --only file.rb` to change only the files listed
4. Adjust exit values so `spoom bump` can more easily used in a script
We can also use all of this to check if files could be bumped to `typed: strict` in our own CI.
See the pull-request #65 for example:
As a matter of fact, this PR is also enabling `spoom bump--from true --to strict --dry` on this repository.
Closes #65.
=> Quality of life improvements to spoom bump

.github/workflows/ruby.yml, .rubocop.yml, Gemfile, Gemfile.lock, dev.yml
This PR aims to improve the GH action to test against multiple ruby versions.
Right now we only know that it works with Ruby 2.6
I'm also introducing tests against Ruby 3.0. It's going to be easier to keep compatibility with all of the stable ruby versions we have right now
=> Testing against multiple ruby versions

lib/spoom/sorbet.rb
It turns up that when we run `sorbet --version`, Sorbet will still read the config file and list all the paths to be analyzed.
On big codebases, this can cost up to 1 second:
```bash
$ time bundle exec srb tc --version
Sorbet typechecker 0.5.6274 git 88e72f6da215d2952b761b0f4398d4296bfc16e3 debug_symbols=true clean=1
real	0m5.551s
$ time bundle exec srb tc --version --no-config
Sorbet typechecker 0.5.6274 git 88e72f6da215d2952b761b0f4398d4296bfc16e3 debug_symbols=true clean=1
real	0m4.545s
```
This pull-request also pass `--no-config` when we ask for Sorbet version to make it faster on larger codebases.
=> Speed up version reading by passing `--no-config` to Sorbet

lib/spoom/cli.rb, lib/spoom/cli/bump.rb, lib/spoom/cli/config.rb, lib/spoom/cli/helper.rb, test/spoom/cli/bump_test.rb
Fix `spoom bump` so it doesn't try to bump files ignored in the `sorbet/config`.
=> Bump uses sorbet/config to know which files to change

lib/spoom/cli/run.rb
This PR makes the default output of the `spoom tc` command to be the condensed form of error messages displayed sorted.
Current errors presentation running `spoom tc`:
Proposed error presentation running `spoom tc`:
=> Condenses default `spoom tc` output and makes the sort option default

Gemfile.lock, lib/spoom/cli/bump.rb, lib/spoom/git.rb, spoom.gemspec, test/spoom/cli/lsp_test.rb
Use the new option introduced in https://github.com/sorbet/sorbet/pull/4078 for Spoom bump.
I locked the version of Sorbet to be greater or equal to the one where the new option is introduced.
=> Use new no error sections option

lib/spoom/cli/bump.rb, test/spoom/cli/bump_test.rb
Add `--count-errors` option to bump, which is similar to a dry run, but prints the number of total errors if all files were bumped to true. No changes are made to the files.
This is useful for measuring typing progress in big code bases where addressing a specific signature or error doesn't unlock the file being `typed: true`, but already reduces the remaining errors to fix.
This is how the output looks. (`bspoom` is just an alias for `bin/spoom`).
=> Add option to count errors if files were bumped to true

README.md
Add a note about the new `--count-errors` option in the README.
=> Add --count-errors to README

lib/spoom/coverage.rb
When building out the file tree for the coverage report, we should respect the users' allowed_extensions configuration if they have it set so that they can see all of the files that they are typing.
=> Respect allowed_extensions in coverage report

lib/spoom/cli/helper.rb, sorbet/config
The `Cli::Helper` actually depends on Thor.
=> Use requires_ancestor instead of `T.unsafe(self)`

lib/spoom/git.rb, test/spoom/git_test.rb
Main change: Add `sorbet_removal_commit` method so one can find when the  `sorbet/config` was removed.
Side change: Return `nil` if no `sorbet_intro_commit` was found. The git log command can return the exit code 0 while nothing matches the search. We add a check to ensure we return `nil` is the output is empty.
=> Find `sorbet/config` removal

lib/spoom/sorbet/sigils.rb, test/spoom/sorbet/sigils_test.rb
Requesting the sigil from a path that points to a directory was ending up in a crash:
```
Sigils.file_strictness("/")
```
```
Errno::EISDIR: Is a directory @ io_fread - /
lib/spoom/sorbet/sigils.rb:59:in `read'
lib/spoom/sorbet/sigils.rb:59:in `file_strictness'
```
With this PR we return `nil` instead.
=> Do not crash when requesting sigil from a directory instead of a file

lib/spoom/coverage.rb
Speed up the computing a bit in case the project contains a lot of errors.
No functional changes.
=> Pass more options to Sorbet when computing coverage metrics

lib/spoom/sorbet/config.rb, test/spoom/sorbet/config_test.rb
When computing typing coverage for a project which use `--no-stdlib` we should pass back this option. Without it, Sorbet will hang or return a bazillion errors.
This PR makes the `Config` parser recognize `--no-stdlib` in the config file and generate it when we ask for the options string.
=> Parse --no-stdlib from config

lib/spoom/cli/bump.rb, test/spoom/cli/bump_test.rb
Try to make the `dry` error message and solution clearer:
=> Make `spoom bump --dry` message more obvious

lib/spoom/cli/coverage.rb, lib/spoom/git.rb, lib/spoom/test_helpers/project.rb, test/spoom/cli/coverage_test.rb
This addresses the issue that spoom would checkout the original commit instead of the original branch when running the coverage command. 
This is a draft PR as I have not figured out how to simulate being on a branch in a test yet, so do not have a test for the behaviour yet.
=> checkout the original branch instead of commit when available

lib/spoom/sorbet/config.rb, test/spoom/sorbet/config_test.rb
=> Ignore comments and blank lines in sorbet/config files (fixes issue #93).

lib/spoom.rb, lib/spoom/sorbet/lsp/structures.rb
`pathname` is in the standard library but not core, so it needs to be required before being used.
Bundler requires it when you use `bundle exec spoom` or a `spoom` binstub:
https://github.com/rubygems/rubygems/blob/master/bundler/lib/bundler/shared_helpers.rb#L3
But it may not always be the case. Also if you don't use Bundler but simply run `gem install spoom && spoom --version`, it fails because of that.
=> Require `pathname`

lib/spoom/cli/bump.rb, lib/spoom/sorbet/errors.rb, test/spoom/cli/bump_test.rb, test/spoom/sorbet/errors_test.rb
The regexp used to parse the error lines produced by Sorbet contained a hard-coded `https://srb.help/` for the error url base.
This meant that when the `spoom bump` command was called on a project containing a custom `--error-url-base` option in its `sorbet/config` file, the parsing went awry and Spoom didn't detect any error in the bumped files resulting in all files being bumped even if it produced thousands or errors.
This PR makes the error-url-base configurable when calling the `Errors::Parser` and override the `--error-url-base` option with a predefined one when calling `spoom bump`.
cc. @RyanBrushett
=> Fix bump command when called with a custom `--error-url-base`

test/spoom/sorbet/run_test.rb
Closes #117.
This was actually order dependent.
If this test is executed first and the gem `sorbet` is not installed
on the system Bundler won't know about it and simply exit with a 127
error code.
Whereas if this test is executed _after_ one installing `sorbet`, Bundler
will see the `srb` executable in the GEM_PATH and raise a different error
(explaining that the executable is not in the bundle) and return 1 instead.
=> Fix flaky `test_run_srb_from_bundler_not_found` test

lib/spoom/sorbet/sigils.rb, lib/spoom/test_helpers/project.rb, test/spoom/cli/bump_test.rb
Fix for #118
Right now, Spoom will remove empty lines after bumping files. My guess is most codebases wouldn't be affected because of enforced magic comments such as `# frozen_string_literal: true`.
Before:
```ruby
class Foo; end
```
After:
```ruby
class Foo; end
```
Adjusting the type sigil regex to only match on horizontal whitespace (tabs and spaces) seems to fix the issue, although there could be additional edge cases to consider.
=> Preserve empty lines when using `spoom bump`

.github/workflows/ruby.yml, Gemfile.lock, sorbet/rbi/gems/thor@1.2.1.rbi, spoom.gemspec
Ruby 2.6 is [EOL since 2022-03-31](https://www.ruby-lang.org/en/downloads/branches/#:~:text=EOL%20date%3A%202022%2D03%2D31).
=> Update Ruby dependency to 2.7

lib/spoom/cli/coverage.rb, test/spoom/cli/coverage_test.rb
--save-dir was removed in #32 however the error message for the
coverage cli command still referenced it. This updates the command
included in the error message to reflect the current available
options.
=> Update coverage cli command to reflect --save option

lib/spoom/cli/run.rb, test/spoom/cli/run_test.rb
Fix issues where `spoom tc` is reporting no error while `srb tc` does report errors when using `--error-url-base`.
We always override the option with a known string when running `spoom tc` so the error parser knows what to look for in the error strings.
=> Override user error-url-base when running Sorbet with `spoom tc`

.github/workflows/ruby.yml
Makes it easier to see errors _before_ opening the PR.
=> Run CI on all branches

Gemfile.lock, test/spoom/cli/coverage_test.rb, test/spoom/cli/lsp_test.rb, test/spoom/snapshot_test.rb, test/spoom/sorbet/run_test.rb, test/test_helper.rb
We didn't bump it in a long time so a few tests were broken following changes upstream.
I fixed them and explained why in each commit description.
=> Bump Sorbet to v0.5.10097

lib/spoom/cli/bump.rb, lib/spoom/sorbet/errors.rb, test/spoom/cli/bump_test.rb, test/spoom/sorbet/errors_test.rb
This PR...
1) Fixes an issue where un-ignoring a file A causes errors in a file B. It fixes this by looking at all related files that show up in the error message and undoing all of their type sigil changes.
2) Documents a bug via a failing test without an immediately clear fix. This probably could be an issue in addition to / instead of the failing test in this PR.
=> Fix bug causing "bump ignore to false" to fail

.github/workflows/ruby.yml
It's no longer experimental since we have it in the matrix.
=> Remove experimental CI for 3.1

service.yml
Fixes https://github.com/Shopify/services/issues/3259.
Following a discussion with the production-excellence team, the file should be kept empty as it is required by `dev` for some commands.
=> Remove `classification` from service.yml

lib/spoom/context.rb, test/spoom/cli/bump_test.rb, test/spoom/cli/cli_test.rb, test/spoom/cli/config_test.rb, test/spoom/cli/run_test.rb, test/spoom/context_test.rb, test/spoom/snapshot_test.rb, test/spoom/sorbet/run_test.rb, test/spoom/sorbet/version_test.rb, test/test_helper.rb
As I was migrating a few clients to use the Context, I noticed a few inconsistencies in the naming that were making the resulting code a bit confusing.
File related methods should all use the `read_`/`write_` prefix if not it's easy to mistake them for actions:
```ruby
bundle_install!
tapioca_config! # would that mean running `tapioca config` or writing to `sorbet/tapioca/config.yml`?
write_sorbet_config! # is more obvious
```
=> Rename some `Context` methods 

.github/workflows/dependabot_automerge.yml
Reduce amount of manual work required by automerging Dependabot PRs that go through successful CI checks
Copied from https://github.com/Shopify/ruby-lsp/pull/227
* Will only run if user is dependabot
* Will only merge if the tests pass
* Human intervention only needed on major versions, merge conflicts, or if the tests fail.
=> Enable automerge for Dependabot PRs

lib/spoom/cli/bump.rb, test/spoom/cli/bump_test.rb
- The previous wording of "No file to bump" sounded weird given that zero is usually referred to in the plural.
- Similarly, Spoom detecting a single file to bump but referring to that single file plurally was confusing as well.
=> cli/bump: Fix "0 or 1 file(s) changed" pluralization

lib/spoom/cli/coverage.rb, lib/spoom/coverage.rb, lib/spoom/git.rb, lib/spoom/timeline.rb, test/spoom/cli/coverage_test.rb, test/spoom/git_test.rb, test/spoom/timeline_test.rb, test/test_project.rb
This abstraction avoids having to call a `git` command twice to get the first the sha and then the timestamp of every single commit.
Beside a slight speedup when computing timelines, this also allows us to remove some unneeded methods.
=> Add `Git::Commit`

lib/spoom/cli/bump.rb, lib/spoom/cli/run.rb, lib/spoom/sorbet.rb, test/spoom/cli/bump_test.rb, test/spoom/cli/run_test.rb, test/spoom/sorbet/run_test.rb
This is PR 1 of 3 to address the issue outlined in this issue: https://github.com/Shopify/spoom/issues/259
1. https://github.com/Shopify/spoom/pull/278
1. https://github.com/Shopify/spoom/pull/279
1. **Add Sorbet killed handling**
In this PR I've added handling in the `Spoom::Sorbet#srb` method to check for the when Sorbet has been killed. This then propagates out in the same way that segfault does, needing explicit `resque`s and output for the error at that place. 
Talking with @Morriar and @KaanOzkan the approach that was landed on was to catch the issue at the Sorbet level and raise an explicit exception for Segfault (exit code: 139) and eventually Killed (exit code: 137). This means that the current handling where we check for segfault can be repalced with rescuing and then outputting …
=> Add Sorbet killed handling

lib/spoom/context.rb
Trying to use `Context.mktmp!` will error if the app does not require `tmpdir` already.
=> Require `tmpdir` in context.rb

lib/spoom/context/sorbet.rb, lib/spoom/coverage.rb
This will avoid a `No errors, good job` to pop in the test output.
=> Always capture the error stream when running `Context#srb_metrics`

test/spoom/cli/bump_test.rb, test/spoom/cli/cli_test.rb, test/spoom/cli/config_test.rb, test/spoom/cli/coverage_test.rb, test/spoom/cli/lsp_test.rb, test/spoom/cli/run_test.rb, test/test_with_project.rb
So one can use a TestWithProject without always running `bundle install` if not needed.
=> Do not always call `bundle_install!` in TestWithProject

.github/workflows/ruby.yml
This should not be necessary since the `bundler-cache: true` setting should handle the setup.
=> Update ruby.yml to skip bin/setup

.github/workflows/ruby.yml, .rubocop.yml, dev.yml, lib/spoom/sorbet/sigils.rb
[Ruby 2.7 is now EOL](https://www.ruby-lang.org/en/downloads/branches/#:~:text=03%2D31%20(expected)-,Ruby%202.7,-status%3A%20eol%0Arelease).
This PR removes support for it.
=> Remove Ruby 2.7 support

lib/spoom.rb, lib/spoom/context/file_system.rb, lib/spoom/deadcode.rb, lib/spoom/deadcode/definition.rb, lib/spoom/deadcode/index.rb, lib/spoom/deadcode/indexer.rb, lib/spoom/deadcode/location.rb, lib/spoom/deadcode/reference.rb, lib/spoom/deadcode/send.rb, test/helpers/deadcode_helper.rb, test/spoom/deadcode/index_definitions_test.rb, test/spoom/deadcode/index_finalize_test.rb, test/spoom/deadcode/index_references_test.rb, test/test_with_project.rb
This is the first step of dead code detection: indexing the Ruby code to find definitions and references.
The concept is somehow easy:
1. Parse the code and:
a. Find the things it defines: constants, classes, modules, methods, etc. and mark it dead
b. Find all the references to things: calling a constant, a class, a method, etc.
2. Once everything is parsed, finalize the index: mark alive all the definitions for which we found a reference with the same name
In the next steps we'll add, parsing ERB files, a plugin system to handle DSLs and meta-programming then the CLI.
This PR is easier to review commit by commit.
=> Introduce indexing for dead code detection

.rubocop.yml, spoom.gemspec
1. Use the lowest version in the Rubocop target as suggested by @vinistock 
2. Update the requirement in the Gemspec as suggested by @andyw8
=> Fix Ruby version requirements

test/test_helper.rb
Fixes #404 
Spoom tests install gems on an instance of `TestProject`, including the most recent version of Sorbet. When Sorbet implements a change that breaks existing Spoom tests, that change will likely be surfaced on CI in an unrelated Spoom PR, which creates a lot of confusion amongst developers as they try to track down the reason for the change.
This PR adds a line that fixes the Sorbet version in Spoom tests to the version in Spoom's Gemfile.lock. This is adapted from the [approach we take in Tapioca](https://github.com/Shopify/tapioca/blob/2cd43f312d6cfd051f7bbaad0202340232e9958c/spec/spec_with_project.rb#L51-L53). Now, tests will only break when Sorbet is bumped in Gemfile.lock, which will make it easier to identify the cause of these breaking tests and reduce confusion.
It looks …
=> Fix `sorbet-static-and-runtime` version in tests

lib/spoom/deadcode.rb, lib/spoom/deadcode/indexer.rb, lib/spoom/deadcode/plugins.rb, lib/spoom/deadcode/plugins/base.rb, lib/spoom/deadcode/plugins/ruby.rb, test/helpers/deadcode_helper.rb, test/spoom/deadcode/plugins/base_test.rb, test/spoom/deadcode/plugins/ruby_test.rb
This PR introduces the base concept for dead code plugins.
The idea is pretty simple, as the indexer visits the code it adds the definitions it finds to the index then calls the plugins to let them ignore those definitions or add references to them.
Here's a very simple example of plugin to ignore a class that has been indexed:
```rb
class MyPlugin < Spoom::Deadcode::Plugins::Base
def on_define_class(indexer, definition)
definition.ignored! if definition.name == "Foo"
end
end
```
This plugin will be called then the indexer processes the `class Foo; end` node. It will call the `on_define_class` from each registered plugin and pass it the indexed `Foo` definition. Note that when `on_define_class` the definition has already been indexed.
Plugins can also be used to handle DSLs and …
=> Introduce dead code plugin base

lib/spoom/deadcode/plugins.rb, lib/spoom/deadcode/plugins/actionpack.rb, lib/spoom/deadcode/plugins/active_job.rb, lib/spoom/deadcode/plugins/base.rb, lib/spoom/deadcode/plugins/minitest.rb, lib/spoom/deadcode/plugins/rails.rb, lib/spoom/deadcode/plugins/rake.rb, test/spoom/deadcode/plugins/actionpack_test.rb, test/spoom/deadcode/plugins/active_job_test.rb, test/spoom/deadcode/plugins/rails_test.rb, test/spoom/deadcode/plugins/rake_test.rb
On top of #420, this PR introduces 3 new DSL methods for dead code plugins:
* `ignore_class_names`
* `ignore_constant_names`
* `ignore_module_names`
=> Ignore constants, classes and modules from dead code plugins

lib/spoom/deadcode/indexer.rb, lib/spoom/deadcode/plugins.rb, lib/spoom/deadcode/plugins/actionpack.rb, lib/spoom/deadcode/plugins/active_job.rb, lib/spoom/deadcode/plugins/active_model.rb, lib/spoom/deadcode/plugins/active_record.rb, lib/spoom/deadcode/plugins/active_support.rb, lib/spoom/deadcode/plugins/base.rb, lib/spoom/deadcode/plugins/graphql.rb, lib/spoom/deadcode/plugins/minitest.rb, lib/spoom/deadcode/plugins/rails.rb, lib/spoom/deadcode/plugins/rake.rb, lib/spoom/deadcode/plugins/rspec.rb, lib/spoom/deadcode/plugins/thor.rb, test/spoom/deadcode/plugins/actionpack_test.rb, test/spoom/deadcode/plugins/active_job_test.rb, test/spoom/deadcode/plugins/active_model_test.rb, test/spoom/deadcode/plugins/active_record_test.rb, test/spoom/deadcode/plugins/graphql_test.rb, test/spoom/deadcode/plugins/minitest_test.rb, test/spoom/deadcode/plugins/rails_test.rb, test/spoom/deadcode/plugins/rake_test.rb, test/spoom/deadcode/plugins/rspec_test.rb, test/spoom/deadcode/plugins/thor_test.rb
When visiting method, we should first add the method to the index _then_ visit its body.
This PR moves the `super` call after the indexing.
Apologies, I merged #436 and #437 by mistake into this branch, please consider only the first commit 🙏
=> Fix indexer visit order

lib/spoom/deadcode/indexer.rb, lib/spoom/deadcode/plugins/base.rb
By making the indexer call the `internal_on_*` method rather than `on_*` directly, we make it easier for plugin implementors to override the public API without breaking internal behavior.
Without this change, if a plugin overrides `on_define_class` and forgets to call `super`, it would break the `ignore_class_names` DSL.
=> Indexer calls internal methods of plugin base

lib/spoom/deadcode/plugins.rb, test/spoom/deadcode/plugins/custom_test.rb, test/spoom/deadcode/plugins_test.rb
This PR introduces two services:
1. `Spoom::Deadcode::plugins_from_gemfile_lock` to instantiate the relevant dead code plugin classes depending on the dependencies found in the Gemfile.lock of the application.
2. `Spoom::Deadcode::load_custom_plugins` to instantiate custom plugins found under `.spoom/deadcode/plugins` so the application can provide custom plugins for DSL that are not handled by default by Spoom.
At this stage, none of these methods are used outside of test until we add the CLI in the next PR.
=> Introduce dead code plugin loading mechanism

README.md, lib/spoom/cli/coverage.rb, lib/spoom/cli/lsp.rb, lib/spoom/context/git.rb, lib/spoom/context/sorbet.rb, lib/spoom/sorbet/errors.rb, lib/spoom/sorbet/lsp/structures.rb, test/spoom/context/sorbet_test.rb, test/spoom/deadcode/plugins/ruby_test.rb
This PR aims to fix various minor typos across the codebase. I noticed some of these when doing the same review on our Homebrew/brew repo, since we use spoom.
=> various: fix miscellaneous typos

README.md, lib/spoom/cli.rb, lib/spoom/cli/deadcode.rb, lib/spoom/deadcode.rb, lib/spoom/deadcode/definition.rb, lib/spoom/deadcode/remover.rb, test/spoom/cli/cli_test.rb, test/spoom/cli/deadcode_test.rb, test/spoom/deadcode/remover_test.rb
Run dead code detection in your project with:
```
$ spoom deadcode
```
This will list all the methods and constants that do not appear to be used in your project.
```
Collecting files...
Indexing 122 files...
Analyzing 1033 definitions against 1128 references...
Candidates:
Spoom::LSP::ResponseError::data lib/spoom/sorbet/lsp/errors.rb:47:18-47:23
Spoom::Deadcode::Remover::NodeRemover::delete_line_part lib/spoom/deadcode/remover.rb:300:8-312:11
Spoom::Deadcode::Indexer::file_name lib/spoom/deadcode/indexer.rb:10:25-10:35
Spoom::LSP::Notification::method lib/spoom/sorbet/lsp/base.rb:62:18-62:25
Found 5 dead candidates
```
You can remove them with Spoom:
```
$ spoom deadcode remove lib/spoom/sorbet/lsp/errors.rb:47:18-47:23
```
This will delete the dead code and show you the resulting diff: …
=> Add CLI commands for detecting and remove dead code

.github/workflows/ruby.yml, .rubocop.yml
The `.ruby-version` file is the ecosystem standard for defining a Ruby version.  This PR adds the `.ruby-version` file, ensures a `required_ruby_version` is set, and removes all other references to Ruby in this repository, aligning it with the standard.
> [!IMPORTANT] 
> Please verify the following before merging:
Verify that the changes in the PR meets the following requirements or adjust manually to make it compliant:
Please merge this PR if it looks good, this PR will be addressed if there isn't any activity after 4 weeks.
=> Centralize Ruby Version to `.ruby-version`

lib/spoom/cli.rb
I noticed that when running `spoom coverage` the warning told me to run `spoom srb bump` instead of `spoom srb coverage`. Just a simple commit to update the deprecation warnings with the correct replacement commands.
=> Update deprecation warnings to be correct

lib/spoom/deadcode/remover.rb, test/spoom/deadcode/remover_test.rb
When the def node contains a `rescue` we were matching against the `BeginNode` location instead of the `DefNode`.
To this this we can stop the descendant lookup as soon as we find a node that as both the right location and kind.
=> Fix removal of def nodes with a rescue

.github/workflows/ruby.yml, spoom.gemspec
Ruby 3.0 is EOL since 2024-04-23.
See https://www.ruby-lang.org/en/downloads/branches/.
=> Remove Ruby 3.0 from CI matrix

lib/spoom.rb, lib/spoom/model.rb, lib/spoom/model/builder.rb, lib/spoom/model/model.rb, lib/spoom/model/namespace_visitor.rb, test/spoom/model/builder_test.rb, test/spoom/model/namespace_visitor_test.rb
While we're working on making the RubyIndexer a standalone gem, we can start making room for it in Spoom so we can base the dead code analysis.
In this PR we create a representation close to what the RubyIndexer builds so we'll be able to use it in dead code analysis in subsequent PRs.
This will allow us to test the concepts and see what's missing to the RubyIndexer API to build other tools than an LSP server.
=> Introduce Model building

lib/spoom.rb, lib/spoom/model/model.rb, lib/spoom/poset.rb, test/spoom/model/model_test.rb, test/spoom/poset_test.rb
A Poset is a set of elements with a partial order relation.
The partial order relation is a binary relation that is reflexive, antisymmetric, and transitive.
It can be used to represent a hierarchy of classes or modules, the dependencies between gems, etc.
Let's take the class hierarchy example as follows:
```rb
class A; end
class B < A; end
class C < B; end
class E; end
```
We can build a POSet representing this class hierarchy:
```rb
poset = Poset[String].new
poset.add_direct_edge("B", "A")
poset.add_direct_edge("C", "B")
poset.add_node(E)
```
And use this poset to answer class inheritance requests:
```rb
assert poset.direct_edge?("B", "A")
refute poset.direct_edge?("C", "A")
assert poset.edge?("C", "A")
c = poset["C"]
assert_equal ["B"], c.parents
assert_equal ["A", "B"], c.ancestors …
```
=> Introduce POSet representation

lib/spoom/cli/deadcode.rb, lib/spoom/deadcode.rb, lib/spoom/deadcode/index.rb, lib/spoom/deadcode/indexer.rb, lib/spoom/deadcode/plugins/base.rb, lib/spoom/deadcode/plugins/namespaces.rb, lib/spoom/deadcode/plugins/rails.rb, test/helpers/deadcode_helper.rb, test/spoom/deadcode/plugins/base_test.rb, test/spoom/deadcode/remover_test.rb
This is the first PR on a sequence moving the dead code analysis use the `Model` introduced in #557 rather than its custom indexer.
In this PR we migrate the indexing of classes:
* Make `Deadcode::Index` take a `Model` (bc1852074a4826acf12d701ee0186515ef8999ba)
* Remove classes indexing from `Deadcode::Indexer` (9433fda1d7f1a6655d9f872af4f579bc30fa9f5e)
* Make the `Deadcode::Plugins` take `Model::SymbolDef` when calling `on_define_class` (635977905fa69baed567f1e04ade5456dde2ade9)
There is no behavior change: no tests are changed.
This PR is easier to review commit by commit.
=> Make dead code indexing use a `Model` to index classes

lib/spoom/deadcode/index.rb, lib/spoom/deadcode/indexer.rb, lib/spoom/deadcode/plugins/base.rb, lib/spoom/deadcode/plugins/rubocop.rb, lib/spoom/deadcode/plugins/sorbet.rb, test/spoom/deadcode/plugins/base_test.rb, test/spoom/deadcode/plugins/sorbet_test.rb
Follow-up on #563.
This time, we switch the indexing of constants to Model:
* Remove constants indexing from Deadcode::Indexer (41250bbb902f373aa3b2d5ba9c751badf70f32c8)
* Make the Deadcode::Plugins take Model::SymbolDef when calling `on_define_constant` (7894f64d094c9e03d987e4a9dfb6410201bc49cc)
There is a slight behavior change, before we were able to look at the nesting context when defining `T::Enum` constants. So with this code:
```rb
class Foo < T::Enum
CONST = new
end
```
We could tell that `CONST` wasn't defined inside a `enums do ... end` block and thus ignore `CONST` within the `sorbet` plugin.
To avoid carrying the `enums do ... end` information and putting pressure on the GC, I dropped this feature, so `CONST` will be marked as `ignored`.
In practice this case doesn't happen …
=> Make dead code indexing use a `Model` to index constants

lib/spoom/deadcode/index.rb, lib/spoom/deadcode/indexer.rb, lib/spoom/deadcode/plugins/base.rb, lib/spoom/model/builder.rb, test/spoom/deadcode/plugins/base_test.rb, test/spoom/model/builder_test.rb
Follow-up on #565/
This time, we switch the indexing of accessors to Model:
* Remove accessors indexing from Deadcode::Indexer + some cleaning (0a5d0dffd12059e817ef6fb8ec1958da91d7be20)
Make the Deadcode::Plugins take Model::SymbolDef when calling `on_define_accessor` (fea73f3b3fd3b107c46bdb28ed012a10514355bb)
There is no behavior change. 
This PR is easier to review commit by commit.
=> Make dead code indexing use a Model to index accessors

lib/spoom/deadcode/plugins/base.rb
So Sorbet can see `index` being defined when writing plugins outside of `Spoom` and thus relying on RBI files.
=> Add public accessor for `Spoom::Plugins::Base#index`

lib/spoom/cli/deadcode.rb, test/spoom/cli/deadcode_test.rb
We had the logic bud never used in the CLI command.
=> Load custom plugins when running `spoom deadcode`

lib/spoom/sorbet.rb, lib/spoom/sorbet/lsp/errors.rb
This makes it easier to rescue `Spoom:Error` from clients
=> Make all errors raised by spoom subclass Spoom::Error

lib/spoom/deadcode/remover.rb, lib/spoom/sorbet/errors.rb
We should always raise a specific error to make it easier for client to rescue properly when something goes wrong.
=> Avoid raising bare runtime errors

lib/spoom/deadcode/plugins/active_model.rb, test/spoom/deadcode/plugins/active_model_test.rb
`ActiveModel::Conversion` defines `to_param` so models can be serialized when passing them through the URL.
Under the hood, `to_param` calls `persisted?` which will need to be defined on the model.
```rb
def to_param
(persisted? && key = to_key) ? key.join('-') : nil
end
```
We should ignore `persisted?` definitions so they do not appear dead.
=> Ignore `persisted?` method definitions

lib/spoom/deadcode/plugins/minitest.rb, test/spoom/deadcode/plugins/minitest_test.rb
* Make plugin ignore classes that inherit from `Minitest::Test` instead of those ending with `Test`
* Modified the `on_define_method` method to ignore methods starting with `test_` or included in the `MINITEST_METHODS` set only when inside a `Minitest::Test` subclass.
* Define `on_send` to mark methods used in `assert_predicate` and `refute_predicate` as alive.
=> Improve deadcode plugin for Minitest

lib/spoom/location.rb, test/spoom/location_test.rb
This PR updates the `Spoom::Location` class to allow the `start_line`, `end_line`, `start_column`, and `end_column` attributes to be `nilable`. This change provides greater flexibility in representing different types of locations within a file.
- **Nilable Attributes**: The `start_line`, `end_line`, `start_column`, and `end_column` attributes of `Spoom::Location` can now be nil.
- **Flexible `Spoom::Location` Representation**:
- Can now represent an entire file, e.g., `foo.rb`.
- It can also represent a range of lines within a file, e.g., `foo.rb:1-3`.
- Maintains previous implementation, with both lines and columns, e.g., `foo.rb:1:2-3:4`.
- **Exception Messages**: Added more detailed messages to exceptions raised within the `Spoom::Location` class to improve debugging and error …
=> Allow nilable Spoom::Location lines and columns attributes

Gemfile.lock, lib/spoom/version.rb
Releasing a new gem version so that `Spoom::Location` start/end line/column can be nilable. (#587)
=> Bump version to v1.4.0

lib/spoom/deadcode/plugins/minitest.rb, test/spoom/deadcode/plugins/minitest_test.rb
Partially reverts https://github.com/Shopify/spoom/pull/579
Not ignoring classes named `*Test` end up resulting in a bug where test classes that inherit from Rails' framework specific test class like `ActiveJob::TestCase` started to be considered dead. https://github.com/Shopify/spoom/pull/592
All of the framework test cases inherit from `ActiveSupport::TestCase` so ultimately it should be enough to have it ignored
https://github.com/Shopify/spoom/blob/d4ccf209f2f244965be77d3644fc646ea26ff613/lib/spoom/deadcode/plugins/active_support.rb#L8
should suffice but at the moment spoom doesn't see the `AJ::TestCase < AS::TestCase` inheritance chain so until we get it fixed we are bringing the `*Test` ignore rule back
=> Ignore `*Test` named classes again

lib/spoom/deadcode/plugins/minitest.rb, test/spoom/deadcode/plugins/minitest_test.rb
Since we only index `.rb` files, the relationship between `ActiveJob::TestCase` and `ActiveSupport::TestCase` and other intermediate classes that may only exist in the RBI files isn't seen by Spoom...
cc. @nvasilevski
=> Revert Improve deadcode plugin for Minitest #579

lib/spoom/cli/srb/sigs.rb, lib/spoom/sorbet/sigs.rb, test/spoom/cli/srb/sigs_test.rb, test/spoom/sorbet/sigs_test.rb
Add a command to strip Sorbet signatures from files.
I refactored the signature translation code to reuse some logic, this PR is easier to review commit by commit.
cc. @dirceu
=> Add `spoom srb sigs strip` command

Gemfile.lock, spoom.gemspec
This gem depends on `rbi` ([here](https://github.com/Shopify/spoom/blob/10a69d3bfe6298d20bf3221e958e7e8c82510151/lib/spoom/sorbet/sigs.rb#L4)), but `rbi` does not appear in the gemspec.
```
$ mkdir spoom-test
$ cd spoom-test
$ bundle init    
$ bundle add spoom
$ bundle exec ruby -r spoom -e 'puts "OK"'
<internal:/Users/rayzane/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- rbi (LoadError)
from <internal:/Users/rayzane/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
from /Users/rayzane/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/spoom-1.5.1/lib/spoom/sorbet/sigs.rb:4:in `<top (required)>'
from <internal:/Users/rayzane/.rbenv/versions/3.2.3/lib/ruby/site_ruby …
```
=> Spoom depends on RBI

Gemfile.lock, spoom.gemspec
We rely on some features from 0.3.0 and some fixes from 0.3.1.
=> Bump rbi requirement to v0.3.1

Gemfile.lock, lib/spoom/cli/srb/tc.rb, lib/spoom/sorbet/errors.rb, rbi/spoom.rbi, spoom.gemspec, test/spoom/cli/srb/tc_test.rb
It's common to use the [JUnit plugin](https://plugins.jenkins.io/junit/) on Jenkins to consume machine-readable output about the tests in your CI builds. For example, on our Ruby app tests we use the [rspec_junit_formatter](https://rubygems.org/gems/rspec_junit_formatter/) to output results from RSpec in a format that Jenkins can consume.
This PR adds JUnit style XML output as an option to Spoom so that running Sorbet in CI on Jenkins can output error information that can be displayed natively by Jenkins (and then, in turn, passed along to e.g. Github's interface).
With these changes Sorbet failures on a build look like this:
and a clean Sorbet build looks like this:
I'm happy to add docs for this feature as well, but I wanted to get initial review of the feature going sooner rather than …
=> Add feature to generate JUnit XML output

Gemfile.lock, lib/spoom/sorbet/sigs.rb, sorbet/rbi/gems/rbi@0.3.3.rbi, spoom.gemspec, test/spoom/sorbet/sigs_test.rb
When using `spoom srb sigs translate --from rbi --to rbs`, this RBI:
```rb
T::Sig::WithoutRuntime.sig { void }
def foo; end
```
will be translated to this RBS:
```rb
#: -> void
def foo; end
```
then with `spoom srb sigs translate --from rbs --to rbi`, back to:
```rb
T::Sig::WithoutRuntime.sig { void }
def foo; end
```
=> Translate `@without_runtime` <> `T::Sig::WithoutRuntime.sig`

lib/spoom/sorbet/translate/rbs_comments_to_sorbet_sigs.rb, test/spoom/sorbet/translate/rbs_comments_to_sorbet_sigs_test.rb
We should not add delete edits whenever we see `@` in the comment. This could cause incorrect ordering in the generated RBI. This commit fixes it by only adding delete edits when we see an annotation.
=> Avoid deleting comments when the comment is not an annotation

lib/spoom/rbs.rb, lib/spoom/sorbet/translate/rbs_comments_to_sorbet_sigs.rb, rbi/spoom.rbi, test/spoom/sorbet/translate/rbs_comments_to_sorbet_sigs_test.rb
Ran into some gems that specify `# @private` which was causing us to insert `extend T::Sig`.
Also a small refactor `Annotations -> Annotation`
=> Fix incorrect `extend T::Helpers` for foreign annotations

lib/spoom/sorbet/translate/sorbet_assertions_to_rbs_comments.rb, rbi/spoom.rbi, test/spoom/sorbet/translate/sorbet_assertions_to_rbs_comments_test.rb
So we translate this:
```rb
T.bind(self, T.class_of(String))
```
into
```rb
#: self as singleton(String)
```
Note that we do not translate bind calls that are not on `self`.
=> Translate `T.bind(self, X)` calls to RBS comments

lib/spoom/sorbet/translate/sorbet_assertions_to_rbs_comments.rb, rbi/spoom.rbi, test/spoom/sorbet/translate/sorbet_assertions_to_rbs_comments_test.rb
We shouldn't blindly translate assertions when they are at the end of the line.
Consider this example:
```rb
a - T.must(b)
```
before this change it would get translated to this:
```rb
a - b #: as !nil
```
which would actually get type checked as this:
```rb
T.must(a - b)
```
=> Only translate top level assertions

lib/spoom/cli/srb/sigs.rb, lib/spoom/sorbet/translate.rb, lib/spoom/sorbet/translate/sorbet_sigs_to_rbs_comments.rb, rbi/spoom.rbi, test/spoom/cli/srb/sigs_test.rb, test/spoom/sorbet/translate/sorbet_sigs_to_rbs_comments_test.rb
By default we won't translate generics, helpers and abstract methods to RBS.
It can be enabled separately:
```
$ spoom srb sigs translate --translate-generics --translate-helpers --translate-abstract-methods
```
=> Make translation of generics, helpers and abstract methods optional

lib/spoom/rbs.rb, test/spoom/sorbet/translate/rbs_comments_to_sorbet_sigs_test.rb
Before this PR, the following example would fail because we tried to use the type alias as the generic signature of the class:
```rb
#: type foo = Integer
class Bar; end
```
=> Do not associate a RBS comment to a node after a blank line
