lib/spoom/cli/commands/config.rb
lib/spoom/sorbet.rb
lib/spoom/sorbet/config.rb
test/spoom/cli/commands/config_test.rb
test/spoom/sorbet/config_test.rb

Using `Spoom::Sorbet::list_files` or the cli command `spoom config files`, one can now list all files belonging to a project that matches Sorbet config.
It takes into account the selected dirs, the ignored strings and the allowed extensions.

Add a way to list all files from a Sorbet project

---

lib/spoom/cli.rb
test/spoom/cli/commands/cli_test.rb

Add a --version option

---

Gemfile.lock
Rakefile
spoom.gemspec

Bump Rake to 13.0.1

---

lib/spoom/cli.rb

Signed-off-by: Alexandre Terrasa <alexandre.terrasa@shopify.com>

Sort the commands definitions

---

lib/spoom/cli.rb
lib/spoom/cli/commands/lsp.rb
lib/spoom/cli/commands/run.rb
test/spoom/cli/commands/cli_test.rb

As to avoid it showing as `--no-no-color` in Thor help.
I also added a test showing the output.

Rename option --no-color => --color

---

lib/spoom/sorbet/errors.rb
test/spoom/sorbet/errors_test.rb

By making sure that we can match the whole line as a proper error line, we can decrease the chances of matching lines that look like error lines, since they are not indented. This can prevent cases like #25 happening in the first place.
This PR introduces a regular expression that matches an error line completely.
In general, this could be much more expensive to do, however, we already had the code to match if a line started with an empty space or not. So, by prefixing the beginning of our error line match to be a non-whitespace character, we can save on scanning the rest of the string for a match. Thus, the full regexp match will only execute on non-indented lines.
The added benefit is that once we match a line to be an error line, we can match all components of it in a single pass and …

Improve error line matching

---

lib/spoom/git.rb
test/spoom/git_test.rb

Signed-off-by: Alexandre Terrasa <alexandre.terrasa@shopify.com>

Strip output of `Git::sorbet_intro_commit`

---

lib/spoom/config.rb

Resolve https://github.com/Shopify/spoom/issues/48

require pathname to fix Unitialized constant

---

Gemfile.lock
lib/spoom/file_tree.rb

Manually bump Sorbet and fix an error.

Bump sorbet

---

test/spoom/cli/coverage_test.rb

Proof we need sigs on Minitest.

Fix an assert that should have been an assert_equal

---

.github/workflows/ruby.yml
lib/spoom.rb
lib/spoom/cli/bump.rb
lib/spoom/cli/coverage.rb
lib/spoom/cli/helper.rb
lib/spoom/cli/lsp.rb
lib/spoom/cli/run.rb
lib/spoom/printer.rb
lib/spoom/test_helpers/project.rb
test/spoom/cli/bump_test.rb
test/spoom/cli/config_test.rb
test/spoom/cli/coverage_test.rb
test/spoom/cli/lsp_test.rb
test/spoom/cli/run_test.rb
test/spoom/sorbet/run_test.rb

Fixing the issues raised in https://github.com/Shopify/spoom/pull/71.
Closes: https://github.com/Shopify/spoom/pull/73.

Run test using `bundle install`

---

lib/spoom/cli/helper.rb
lib/spoom/cli/run.rb

Fixing undefined method errors that were introduced in #103.

Fix error in `spoom tc`

---

Gemfile
Rakefile
bin/console
exe/spoom
lib/spoom.rb
lib/spoom/sorbet.rb
lib/spoom/sorbet/errors.rb
spoom.gemspec

Getting things to a darker shade of green:

Bump a few files to `typed: strict`

---

lib/spoom/sorbet/lsp.rb
lib/spoom/sorbet/lsp/base.rb
lib/spoom/sorbet/lsp/errors.rb
lib/spoom/sorbet/lsp/structures.rb

Bump lsp files to `typed: strict`

---

.github/workflows/ruby.yml

Leftover from https://github.com/Shopify/spoom/pull/171.

Remove bad value for `continue-on-error`

---

.vscode/launch.json
Gemfile
Gemfile.lock

Switch to the official Ruby debugger. The last release of `byebug` was almost 3 years ago.
Closes https://github.com/Shopify/ruby-dev-exp-issues/issues/747

Use ruby/debug

---

lib/spoom/context/git.rb
test/spoom/cli/coverage_test.rb
test/spoom/context/git_test.rb
test/test_project.rb

1. Change `git_commit!` to return an ExecResult, this makes it easier to see if the commit command failed
2. Introduce `git_checkout_new_branch`, to move to a new branch based on a ref
3. Introduce `git_push!`, to push changes to a remote repo

Add a few more Context::Git related methods

---

lib/spoom/deadcode/erb.rb

From comment https://github.com/Shopify/spoom/pull/375#discussion_r1224566804.
@rafaelfranca is it what you had in mind?

Add license to copied file from Rails

---

lib/spoom/sorbet.rb
test/test_helper.rb

Related to #404. Responds to @Morriar's [comment](https://github.com/Shopify/spoom/pull/406#discussion_r1242251659) in #406.

In `test_helper`, specify Sorbet version as a constant

---

lib/spoom/deadcode/plugins.rb
lib/spoom/deadcode/plugins/action_mailer.rb
lib/spoom/deadcode/plugins/actionpack.rb
lib/spoom/deadcode/plugins/active_model.rb
lib/spoom/deadcode/plugins/active_record.rb
lib/spoom/deadcode/plugins/base.rb
lib/spoom/deadcode/plugins/graphql.rb
lib/spoom/deadcode/plugins/ruby.rb
lib/spoom/deadcode/send.rb
test/spoom/deadcode/plugins/action_mailer_test.rb
test/spoom/deadcode/plugins/actionpack_test.rb
test/spoom/deadcode/plugins/active_model_test.rb
test/spoom/deadcode/plugins/active_record_test.rb
test/spoom/deadcode/plugins/graphql_test.rb

This adds more dead code plugins that react to `on_send`.

Add plugin behavior on `on_send`

---

README.md

Related https://github.com/Shopify/spoom/issues/489.

Better explanation for `bump --dry`

---

Gemfile.lock
lib/spoom/version.rb

Preparing a release to ship https://github.com/Shopify/spoom/pull/593 change
Is bumping patch version okay?

Prepare v1.4.1 release

---

lib/spoom/deadcode/plugins/ruby.rb
test/spoom/deadcode/plugins/ruby_test.rb

Closes https://github.com/Shopify/spoom/issues/606.

Add deadcode plugin handling for Object#method
